export { default as Home } from "./Home";
export { default as News } from "./News";
export { default as Equipment } from "./Equipment";
export { default as Profile } from "./Profile";
export { default as Rent } from "./Rent";
export { default as Login } from "./Login";
export { default as SignUp } from "./SignUp";
export { default as Password } from "./Password";
export { default as Default } from "./Default";
